server:
  port: 9999

spring:
  application:
    name: manage-system
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/manager?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: maple
      password: maple
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: js/**,css/**,common/**
      cache: false
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
      select-strategy: not_empty
  type-enums-package: com.maple.common.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
auth:
  login-url: /login
  success-url: /home
  unauthorized-url: /error
  filter-chain:
    # 放行登录页面
    - /login:anon
    # 配置退出过滤器,具体的退出代码Shiro已经实现
    - /logout:logout
    # 放行登陆验证
    - /user/checkLogin:anon
    # 放行错误页面
    - /error/**:anon
    # 放行swagger文挡
    - /doc.html:anon
    - /swagger-resources/**:anon
    - /swagger-ui.html:anon
    - /v2/**:anon
    - /webjars/**:anon
    # 配置记住我或认证通过可以访问的地址
    - /user/userList:user
    - /:user
    # 配置静态资源放行
    - /css/**:anon
    - /common/**:anon
    - /js/**:anon
    - /images/*/**:anon
    - /user/login:anon
    # 其他所有url都必须认证通过才可以访问
    - /**:kickout,authc